# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='updated',
        ),
        migrations.AddField(
            model_name='trip',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('', 'on_trip'), ('', 'available'), ('', 'off_duty')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('ongoing', 'ongoing'), ('complete', 'complete')], db_index=True, default='waiting', max_length=8),
        ),
    ]
